server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/weblog?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    #mapper.xml所在位置
    mapper-locations: classpath:mapper/*Mapper.xml
    #实体类所做包
    type-aliases-package: com.domain.model
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql

