server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/weblog?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    jackson:                                                      #rest 返回时间设置格式
      date-format: yyyy-MM-dd                                    #时间格式
      time-zone: GMT+8                                           #时区别
      serialization:
        write-dates-as-timestamps: false                         #是否使用时间戳作为格式
    thymeleaf:
      cache: false                                                #模版在开发时候不使用缓存
      prefix: classpath:/templates/                               #前缀
      suffix: .html                                               #后缀

mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml              #mapper.xml所在位置
    type-aliases-package: com.domain.model                      #实体类所做包
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
logging:                                                          #日志设置
    file: target/app.log                                          #日志记录位置
    level:
      ROOT: info                                                  #日志配置级别
      controller: info                                            #日志启动的
