server:
    port: 8082
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/weblog?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.weblog.model
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql